package com.AZapps.retrofit;

import com.google.gson.annotations.SerializedName;

public class Post {
    private int userId;
    private int id;
    private String title;
    // if the name of your var differs form the one you will get from the api
    // you should annotate it with SerializedName("name of the api var")
    @SerializedName("body")
    private String text;


    public Post(int userId, String title, String text) {
        // we do not add the id as it will be generated by retrofit
        this.userId = userId;
        this.title = title;
        this.text = text;
    }

    public int getUserId() {
        return userId;
    }

    public int getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getText() {
        return text;
    }
}


